{% set version = "3.0.1" %}

package:
  name: libtensorlight
  version: {{ version }}

source:
  url: https://github.com/adc-connect/libtensor/archive/v{{ version }}.tar.gz
  patches:
    - 0001-add-netlib-blas-remove-tabs.patch
  sha256: 1ec596bbd160b4df413bccb42e88d876e098aa62899f6b1bb50003d5552bf9cb

build:
  number: 6
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libtensorlight', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}                      # [not osx]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - mkl-devel                              # [x86_64]
    - blas-devel                             # [not x86_64]
    - libblas * *netlib                      # [not x86_64]
    - llvm-openmp            # [osx]
    - libgomp                # [linux]
    - cmake >=3.2
    - ninja

  host:
    - mkl-devel                              # [x86_64]
    - blas-devel                             # [not x86_64]
    - libblas * *netlib                      # [not x86_64]

  run:
    - mkl                                    # [x86_64]
    - libblas * *mkl                         # [x86_64]
    - libblas                                # [not x86_64]
    - libcblas                               # [not x86_64]

test:
  commands:
    - test -f $PREFIX/lib/libtensorlight$SHLIB_EXT

about:
  home: https://github.com/epifanovsky/libtensor
  dev_url: https://github.com/adc-connect/libtensor
  license: BSD-1-Clause
  license_family: Other
  license_file: LICENSE
  summary: "C++ library for tensor computations"

extra:
  recipe-maintainers:
    - maxscheurer
